### ISSUE TITLE
Define common coding style to follow

### ISSUE THREAD

**Issue by georgehristov** [atk4/infrastructure#10]
Suggested PSR-12
For instance PSR-2 recommends avoiding and PSR-12 forbids using underscores to indicate protected/private properties and methods.
These are still common in all the packages and even in new features.

**Comment by DarkSide666** [comment]
I don't see anything bad about using underscores in such case.

**Comment by romaninsh** [comment]
PSR-12 cannot be enforced on the infrastructure level. Also - this decision can be made on per-repository basis.

We probably can create "github project" to group all the issues and gradually organise ourselves to clean up repositories.

**Comment by mvorisek** [comment]
I think underscores are helpfull for some special properties/methods, but otherwise the current CS fixer config should be enforced for all repos. And preferable distributed centrally. Any issues can be the fixed manually in the target repos.

**Comment by mvorisek** [comment]
@romaninsh is it possible to distribute common files thru this repo like the CS fixer config, ie. auto create PR in target repo if one or more file is missing/different? And can we use some templating if for one repo we need a slightly different file?

TODO:
- create central/unified CS fixer config from https://github.com/atk4/core/blob/develop/.php_cs.dist
- created central/unified phpunit config from https://github.com/atk4/core/blob/develop/phpunit.xml.dist - incl. support for multiple files for atk4/data

Also remove the wont't fix label, 👍 for @georgehristov for this issue.

**Comment by romaninsh** [comment]
@romaninsh it's possible to implement a "template" repository - for example we can have one and use it for all new add-ons. 

It is also possible to create a workflow that uses GitHub API to close repositories, update files and if necessary commit those files back. Finally we can place the CS files into a separate repository and fetch those files inside workflows (kinda like submodules)

Which option you would think is best?

**Comment by romaninsh** [comment]
closing this - as this can be solved on individual repository basis.
