### ISSUE TITLE
Define list of common labels to be applied to all add-on repositories

### ISSUE THREAD

**Issue by romaninsh** [atk4/infrastructure#2]
Here is my list, but please suggest more:

 - hangout agenda
 - review
 - ..

**Comment by mvorisek** [comment]
Just sort all labels by use count across all repos.

**Comment by romaninsh** [comment]
1. https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aatk4+label%3Aquestion <-- this can be used to search for most common labels to create a list
2. labels that use emoji/images - need to be properly formatted
3. have to use this format: https://github.com/atk4/infrastructure/blob/master/projects/agiletoolkit.org/github/agiletoolkit.org/addon/addon-repo.tf#L17

```
  labels = {
    "PHP7.3+" : { c: "FF0000", d: "This can only run on PHP 7.3 and higher" }
  }
```
4. create PR.

**Comment by mvorisek** [comment]
Ad 1 - open labels from core, ui, data, ... ex. https://github.com/atk4/ui/issues/labels?sort=count-desc
